[build]
  publish = "_site"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "v8.4.0"

[[headers]]
  for = "/*"

  [headers.values]
    Cache-Control = "public, max-age=2628000, must-revalidate"
