[build]
  publish = "_site"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "v8.4.0"

[[headers]]
  for = "/*"

  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Link = [
      "</assets/js/scripts.min.js>; rel=preload; as=script",
      "</assets/css/style.min.css>; rel=preload; as=style"
    ]
